### ISSUE TITLE
Dispersion bug in `compute_lpd()` for `integrated = TRUE`?

### ISSUE THREAD

**Issue by fweber144** [stan-dev/projpred#105]
At least for the `gaussian()` family, specifying `integrated = TRUE` in `proj_linpred()` probably leads to an incorrect usage of the dispersion parameter values when calculating output element `lpd`. Consider the following reprex:
```r
library(projpred)
library(rstanarm)
options(mc.cores = parallel::detectCores(logical = FALSE))
data("df_gaussian", package = "projpred")
mydat <- cbind("y" = df_gaussian$y, as.data.frame(df_gaussian$x))
myfit <- stan_glm(y ~ V1 + V2 + V3 + V4 + V5,
                  family = gaussian(),
                  data = mydat,
                  prior = hs(df = 1, global_scale = 0.01),
                  seed = 1140350788)

debugonce(projpred:::compute_lpd)
mylinpred <- proj_linpred(myfit,
                          solution_terms = c("V3", "V2"),
                          newdata = mydat[1:3, , drop = FALSE],
                          integrated = TRUE,
                          ndraws = 20)
```
Then, while in debugging mode, you'll see that in line https://github.com/stan-dev/projpred/blob/f3962c0672d3ddbe6e184625c0e549a0392ba7c9/R/methods.R#L225 object `proj$dis` is a vector of length 20 but should probably be a vector of length 3 instead to match object `pred`.

**Comment by AlejandroCatalina** [comment]
Fixed upstream.

**Comment by fweber144** [comment]
Thanks for addressing this in commit 26d83e63c8a7f28bff44a9be002ed72c65ed273f. However, the implementation now relies on proper recycling of the arguments passed to `proj$family$ll_fun()` which is not the case I think: When debugging the reprex from above until line https://github.com/stan-dev/projpred/blob/daeb377b85dd50edf3c81158807aa620c4ce975b/R/methods.R#L227 I get:
```r
str(pred)
# num [1:20, 1:3] 0.905 1.316 1.393 1.019 1.321 ...
# - attr(*, "dimnames")=List of 2
# ..$ : NULL
# ..$ : chr [1:3] "1" "2" "3"
str(proj$dis)
# num [1:20] 2.9 2.79 2.99 2.9 2.7 ...
str(ynew)
# num [1:3] -1.275 1.843 0.459
str(weights)
# num [1:3] 1 1 1
```
which together with https://github.com/stan-dev/projpred/blob/26eefd61d2127d9900610ee95656ecca6477473e/R/extend_family.R#L126-L129 doesn't lead to proper recycling, right?

**Comment by AlejandroCatalina** [comment]
I’m not sure what you mean by recycling now?

Best,
Alejandro

**Comment by fweber144** [comment]
[This](https://www.oreilly.com/library/view/the-art-of/9781593273842/ch02s03.html). For `integrated = TRUE`, you have fixed it correctly (you are right; of course `proj$dis` also needs to be averaged over the posterior draws). However, for the default of `integrated = FALSE`, I think recycling is still not performed properly. Simply change the last call from the reprex above to
```r
mylinpred <- proj_linpred(myfit,
                          solution_terms = c("V3", "V2"),
                          newdata = mydat[1:3, , drop = FALSE],
                          ndraws = 20)
```
and then, when debugging the reprex from above until line https://github.com/stan-dev/projpred/blob/daeb377b85dd50edf3c81158807aa620c4ce975b/R/methods.R#L227 I get:
```r
str(pred)
# num [1:20, 1:3] 0.995 1.599 1.078 1.171 1.3 ...
# - attr(*, "dimnames")=List of 2
# ..$ : NULL
# ..$ : chr [1:3] "1" "2" "3"
str(proj$dis)
# num [1:20] 2.86 2.76 2.99 2.74 2.77 ...
str(ynew)
# num [1:3] -1.275 1.843 0.459
str(weights)
# num [1:3] 1 1 1
```
which together with https://github.com/stan-dev/projpred/blob/26eefd61d2127d9900610ee95656ecca6477473e/R/extend_family.R#L126-L129 doesn't lead to proper recycling, which may be seen from running
```r
dis_tmp <- matrix(rep(proj$dis, each = length(ynew)), ncol = NCOL(pred))
str(dis_tmp)
# num [1:20, 1:3] 2.86 2.86 2.86 2.76 2.76 ...
```
while debugging as above. I think either `pred` needs to be transposed in line https://github.com/stan-dev/projpred/blob/daeb377b85dd50edf3c81158807aa620c4ce975b/R/methods.R#L227 or the log-likelihood function has to use
```r
dis <- matrix(rep(dis, each = length(y)), ncol = NCOL(mu), byrow = TRUE)
```
or
```r
dis <- matrix(rep(dis, times = length(y)), ncol = NCOL(mu))
```
instead of https://github.com/stan-dev/projpred/blob/26eefd61d2127d9900610ee95656ecca6477473e/R/extend_family.R#L127 but changing the log-likelihood function might have undesirable side-effects at other places in the code.

**Comment by fweber144** [comment]
Yes, seems to work correctly now with commit cc7d0d6. The only thing which has to be kept in mind now with commit cc7d0d6 is that in case of `integrated = TRUE`, `pred` will be a 1xN matrix (and not a Nx1 matrix or a length-N vector) inside of `compute_lpd()`. But that doesn't seem to affect the proper recycling (as `proj$dis` should be a scalar in that case, so will be augmented to a 1xN matrix within the log-likelihood function, too) and the output object seems to be fine, too.
