### ISSUE TITLE
README example yields an error

### ISSUE THREAD

**Issue by aaelony-catasys** [stan-dev/projpred#127]
Following the example in the README file up to the line:

```
vs <- varsel(fit)
```
yields 

```
Error in eval(predvars, data, env) : object 'x1' not found
```

**Comment by AlejandroCatalina** [comment]
Thanks for reporting.

This is now fixed on develop https://github.com/stan-dev/projpred/commit/756eb8e6435da975348ef9d46ed11b1f61297353.

**Comment by aaelony-catasys** [comment]
Hi - thanks for the speedy correction!  Can you point me to build instructions?  What is the best way to build the source in the develop branch to try it out in R?

**Comment by aaelony-catasys** [comment]
The following installed for me:

`devtools::install_github('stan-dev/projpred', ref = "develop", build_vignettes = TRUE)`

but, following the README example, I did have to increase the value of `iter = 500`, to avoid the warning message:
```
Warning message:                                                                                                                                       
Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable. 
```
and I do still receive an error for 

```
vs <- varsel(fit)
Error in eval(predvars, data, env) : object 'x1' not found
```

**Comment by AlejandroCatalina** [comment]
So, the fix is the readme code. The problem with the current code is that `df_gaussian` has only two columns x and y but x is a whole matrix. You just need to run this code

```
split_structure <- break_up_matrix_term(y ~ x, data = df_gaussian)
df_gaussian <- split_structure$data
formula <- split_structure$formula

# fit the full model with a sparsifying prior
fit <- stan_glm(formula, family = gaussian(), data = df_gaussian,
 prior = hs(df = 1, global_scale=0.01), iter = 500, seed = 1)
#fit <- stan_glm(formula, family = binomial(), data = df_binom
# prior = hs(df = 1, global_scale=0.01), iter = 500, seed = 1)


# perform the variable selection
vs <- varsel(fit)
```

And now it should run.

Best,
Alejandro
