### ISSUE TITLE
Broken reference example

### ISSUE THREAD

**Issue by avehtari** [stan-dev/projpred#59]
Custom reference model initialization reference
https://mc-stan.org/projpred/reference/init_refmodel.html
shows lot of errors 
```
fit <- stan_glm(y~x, family=gaussian(), data=data.frame(x=I(x),y=y))
#> Error in stan_glm(y ~ x, family = gaussian(), data = data.frame(x = I(x),     y = y)): could not find function "stan_glm"
draws <- as.matrix(fit)
#> Error in as.matrix(fit): object 'fit' not found
```

**Comment by AlejandroCatalina** [comment]
As far as I can tell, this is happening due to failing to load `rstanarm`, which presumably is caused by not being able to update `rstan`. Can we do anything about this? (The latest commit on develop also fails on Travis because of the same issue). We don't depend on `rstanarm` or `rstan` directly but every chunk of code that loads them will have this issue, which is worrying.

**Comment by AlejandroCatalina** [comment]
This has been fixed with the release.

**Comment by giadaleone99** [comment]
Hey Alejandro, just wondering how you solved the  issue with rstanarm. 

When Trying to run a stan_glm i get the error could not find function "stan_glm"

Just wondering what you meant by this has been fixed with the release? 

Thanks,

Giada

**Comment by AlejandroCatalina** [comment]
I’m not sure I understand the problem. If R says `stan_glm` is not defined, did you make sure to load the rstanarm library?

From: Giada Leone ***@***.***>
Date: Wednesday, 10. November 2021 at 14.18
To: stan-dev/projpred ***@***.***>
Cc: Alejandro Catalina ***@***.***>, State change ***@***.***>
Subject: Re: [stan-dev/projpred] Broken reference example (#59)

Hey Alejandro, just wondering how you solved the issue with rstanarm.

When Trying to run a stan_glm i get the error could not find function "stan_glm"

Just wondering what you meant by this has been fixed with the release?

Thanks,

Giada

**Comment by giadaleone99** [comment]
Yes, so I have installed the package and loaded the library, yet I still get this error:

Error in stan_glm(Richness ~ I(Year - 2007), data = toolik_richness, family = poisson,  : 
  could not find function "stan_glm"

**Comment by AlejandroCatalina** [comment]
I’m afraid this error is unrelated to projpred. You might want to check with rstanarm itself first.

From: Giada Leone ***@***.***>
Date: Wednesday, 10. November 2021 at 14.21
To: stan-dev/projpred ***@***.***>
Cc: Alejandro Catalina ***@***.***>, State change ***@***.***>
Subject: Re: [stan-dev/projpred] Broken reference example (#59)

Yes, so I have installed the package and loaded the library, yet I still get this error:

Error in stan_glm(Richness ~ I(Year - 2007), data = toolik_richness, family = poisson, :
could not find function "stan_glm"
